# Generated by Django 4.2.7 on 2023-12-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="friendrequest",
            name="request_id",
            field=models.CharField(default="765675", max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
